name: app
description: QuickGrab - Reinventing offline shopping

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.13.5
  cuberto_bottom_bar: ^1.1.0
  firebase_messaging: '^6.0.12'
  google_map_location_picker: ^3.2.1+2
  dart_geohash: ^1.0.2
  latlong: ^0.6.1
  map_launcher: ^0.4.3
  google_maps_flutter:
  url_launcher: any
  flutter_datetime_picker: ^1.3.5
  jiffy: ^3.0.1
  flappy_search_bar: 1.4.1
  badges: ^1.1.1
  image_picker: ^0.6.6+1
  image_cropper: ^1.2.2
  firebase_database: ^3.1.5
  firebase_storage: ^3.0.3
  flutter_swiper : ^1.1.6
  carousel_slider: ^2.1.0
  rating_dialog: ^1.0.0
  share: ^0.6.4+2
  quiver: 2.1.3
  ticket_pass_package: ^0.1.0
  flutter_facebook_login:
    git:
      url: 'git://github.com/romulojjunior/flutter_facebook_login.git'
      ref: 'v1.3.0-web'
  flutter_auth_buttons: ^0.8.0
  flutter_advanced_networkimage: ^0.7.0
  universal_platform: ^0.1.3
  grouped_list: ^3.0.0
  flutter_google_places: ^0.2.5
  google_maps_webservice: ^0.0.16
  mdi: ^2.0.0
  firebase_admob: ^0.9.3+2
  device_id: ^0.2.0
  flutter_native_admob: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          style: normal
        - asset: assets/fonts/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          style: normal
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 100
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: CircularBook
      fonts:
        - asset: assets/fonts/CircularBook.ttf
          style: normal

    - family: Attitude
      fonts:
        - asset: assets/fonts/Attitude-Regular.otf
          style: normal

    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
          style: normal
        - asset: assets/fonts/Proxima_Nova_Thin.otf
          weight: 100
        - asset: assets/fonts/Proxima_Nova_Thin.otf
          weight: 300
        - asset: assets/fonts/Proxima_Nova_Bold.otf
          weight: 700

    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.ttc

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
